languageCode = "fr-fr"
title = "Breizh Coast Swing"
baseurl = "http://www.breizhcoastswing.fr"
theme = "bcs-theme"

[params]

  name = "my2hands"
  description = "Stages de West Coast Swing à Rennes"

  custom_css = []
  custom_js  = []
  # favicon    = "favicon.ico"

  disableFonts = false

  [params.error404]
    heading = "La page que vous recherchez est introuvable"
    text = "Rendez-vous sur notre page d'accueil [Breizhcoastswing.com](/)"

  # Navigation
  [params.navigation]
    brand = "Breizh Coast Swing"
    presentation = "Présentation"
    about = "Les professeurs"
    planning = "Le planning"
    price = "Les Tarifs"
    registration = "Inscription"

  # Hero section
  [params.hero]
    title = "Vous avez aimé le Breizh Coast Swing 3 en février 2018 ? <br />Alors vous aimerez plus encore le"
    subtitle = "Breizh Coast Swing 4"
    buttonText = "En savoir plus"

  # Presentation section
  [params.presentation]
    enable = true
    title = "Présentation"
    subtitle = "Un stage à taille humaine avec un super couple de professeurs !"
    description = """Nous avons l'honneur d'accueillir<br /><br />
      <span style="color: #51161c; font-weight: bold; font-size: 1.5em">Estelle BONNAIRE</span> et <span style="color: #51161c; font-weight: bold; font-size: 1.5em">David CLAVILIER</span><br /><br />
      Venez découvrir la grâce d’Estelle et la classe de David, ils sauront vous ravir !<br /><br />
      Alors rendez-vous les 16 et 17 février 2019 !<br /><br />
      Ce stage est organisé par Hélène BURY et l'association <a href="http://www.fun-club-35.com/"><strong>FUN CLUB 35</strong></a>."""

  # About section
  [params.about]
    enable = true
    title = "Les professeurs"
    subtitle = "Estelle BONNAIRE et David CLAVILIER"
    endpoint = """<div class="iframeWrapper">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/V0lzTvf39M0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div><br /> <br />
      <div class="iframeWrapper">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/Y7mu7xn4cH8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>"""

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.trainer]]
      img = "estelle_bonnaire_avatar.jpg"
      title = "Estelle"
      description = """C'est à l'âge de 14 ans qu'elle commence la danse avec le Lindy Hop. Une vraie
        passion et un art de vivre qui la fascinent et la poussent à voyager et apprendre le
        plus possible concernant les danses Swing. C'est alors qu'elle découvre le West
        Coast Swing et réalise qu'il s'agit ici de la danse parfaite pour elle, alliant
        technique, fluidité et Swing. <br /><br />
        Elle déménage à Montréal en 2011 et s'y installe
        pendant 2 ans pour pouvoir apprendre encore et se perfectionner en compétition,
        elle est actuellement en niveau All Star et a pu suivre des formations
        professionnelles diverses dans cette danse.<br /><br />
        Elle est maintenant à la tête de son association de WCS Move Addict à Montpellier."""

    [[params.about.trainer]]
      img = "david_avatar.jpg"
      title = "David"
      description = """David commence le rock'n roll à l'âge de 12 ans, puis se lance très vite dans la pratique du Boogie Woogie.
        A 13 ans il débute la compétition et obtient de nombreux titres de champion de France dans ces deux disciplines.<br /><br />
        Plus récemment, David s'est pris de passion pour le West Coast Swing, danse beaucoup plus moderne, destinée à un public beaucoup plus large.
        Il participe depuis à des compétitions internationales dans lesquelles il a pu atteindre, en une année,
        le niveau Advanced (l'une des plus hautes catégories)."""

  # Planning section
  [params.planning]
    enable = true
    title = "Le planning"
    subtitle = "3 niveaux de 3 heures chacun"

    interLevelDate = """Attention : il n’y aura pas de test de niveau, néanmoins les professeurs
      et organisateurs se réservent la possibilité de vous faire changer de niveau(x) si celui
      (ou ceux) que vous avez choisi(s) n’est (ou ne sont) pas approprié(s) !
      <br /><br />Les cours seront répartis comme suit :"""

    bottomPlanning = """Merci d'arriver 15 min avant votre cours.<br /><br />
      <span style="color: #51161c; font-weight: bold;">Les cours et la soirée du samedi</span> auront lieu à Dance Gallery, 20 rue Perrin de la Touche, 35000 Rennes.<br /><br />
      <i>Merci de bien vouloir vous garer correctement par respect pour les voisins : les places privatives, entrées de garages, … des voisins et les lignes jaunes au sol sont à respecter.</i><br />
      <i>Le rond-point en face de Dance Gallery n'est pas un parking, il est interdit de s'y garer.</i><br />
      <i>Si avec votre voiture, sur le parking de Dance Gallery, vous bloquez un ou plusieurs autres véhicules, merci d’avance de mettre sur votre tableau de bord vos nom et prénom visiblement pour être facilement trouvable sans avoir à interrompre les cours ou la soirée.</i><br /><br />
      <span style="color: #51161c; font-weight: bold;">Les cours du dimanche</span> auront lieu à L’Espace des Deux Rives, 4 allée Georges Palante à Rennes.<br /><br />
      <i>Un parking souterrain est accessible pour les membres des cours, il suffit de s'avancer afin d'ouvrir la porte du parking.</i>
      <br /><br />
      <div class="iframeWrapper">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2663.405260230934!2d-1.6905426847542313!3d48.12170756024573!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x480ede248e83974d%3A0x16e41597e798d823!2sDance+Gallery!5e0!3m2!1sfr!2sfr!4v1447616147766" width="853" height="480" frameborder="0" style="border:0" allowfullscreen=""></iframe>
      </div>
      <br />
      <div class="iframeWrapper">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2664.101176856498!2d-1.662291848402528!3d48.10828392911922!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x480edfaccb425d65%3A0xb588b937b5a1fa97!2sEspace+des+2+Rives!5e0!3m2!1sfr!2sfr!4v1514498208699" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
      """

    [[params.planning.level]]

    [[params.planning.level.list]]
      title = "Débutant"
      description = "Vous avez commencé le WCS en septembre 2018, ce niveau est pour vous !"
      url = "#planning"

    [[params.planning.level.list]]
      title = "Intermédiaire"
      description = """Vous avez au moins 1 an et demi de cours,
        vous participez à toutes les soirées au cours desquelles vous dansez sur
        tous les tempo sans problème, ceci est votre niveau !"""
      url = "#planning"

    [[params.planning.level.list]]
      title = "Avancé"
      description = """Vous dansez depuis au moins 3 ans et faites tous les stages de la région,
        voire de France et d’Europe ! :-) Vous êtes un mordu de WCS, ceci est votre niveau !"""
      url = "#planning"

    [[params.planning.date]]

    [[params.planning.date.list]]
      title = "Samedi"
      hours = [
        "Accueil des stagiaires dès 13h",
        "13h30 à 15h00 - Débutant",
        "15h20 à 16h50 - Intermédiaire",
        "17h10 à 18h40 - Avancé"
      ]
      url = "#planning"

    [[params.planning.date.list]]
      title = "Soirée"
      hours = [
        "A partir de 21h30"
      ]
      url = "#planning"

    [[params.planning.date.list]]
      title = "Dimanche"
      hours = [
        "Accueil des stagiaires dès 13h30",
        "13h00 à 14h30 - Avancé",
        "14h45 à 16h15 - Intermédiaire",
        "16h30 à 18h00 - Débutant"
      ]
      url = "#planning"

  # Price section
  [params.price]
    enable = true
    title = "Les tarifs"

    [[params.price.date]]

    [[params.price.date.list]]
      title = "Du 26 novembre au 20 décembre 2018"
      price = [
        "1 niveau (3h) : 40 euro",
        "2 niveaux (6h) : 70 euro",
        "3 niveaux (9h) : 100 euro"
      ]
      url = "#price"

    [[params.price.date.list]]
      title = "Après le 20 décembre 2018"
      price = [
        "1 niveau (3h) : 50 euro",
        "2 niveaux (6h) : 80 euro",
        "3 niveaux (9h) : 110 euro"
      ]
      url = "#price"

    [[params.price.date.list]]
      title = "Soirée du samedi soir"
      price = [
        "Incluse pour les stagiaires",
        "10 euro pour les extérieurs"
      ]
      url = "#price"

    [[params.price.condition]]

    [[params.price.condition.list]]
      title = "Confirmation des inscriptions"
      description = """Les inscriptions ne seront confirmées qu'à réception du
        règlement que vous pouvez soit me remettre en main propre, soit m'envoyer à l'adresse suivante :<br /><br />
        Hélène BURY<br />
        13 rue Renée Prévert<br />
        35000 RENNES<br /><br />
        Merci de libeller vos chèques à l'ordre de l'association « FUN CLUB 35 »."""
      url = "#price"

    [[params.price.condition.list]]
      title = "Conditions d'annulation"
      description = """En cas d'annulation jusqu'à 2 mois du stage, nous vous remboursons le stage mais conservons 10 euro pour frais de gestion<br /><br />
      Entre 2 mois et 15 jours du stage, nous vous remboursons 50 % du prix du stage<br /><br />
      À moins de 15 jours du stage (y compris pour cause de blessure ou de train ou de vol annulé), nous serons au regret de ne pouvoir vous rembourser"""
      url = "#price"

  # Registration section
  [params.registration]
    enable = true
    title = "Inscription"
    description = """Pour vous inscrire, merci d'envoyer un email via ce formulaire tout en précisant les éléments suivants :
    <ul style="color: #ffffff">
      <li class="large">Si vous êtes Follower ou Leader</li>
      <li class="large">Votre niveau de pratique (débutant, intermédiaire, avancé)</li>
      <li class="large">Le nom de votre partenaire dans le cas ou vous faites une inscription en couple</li>
      <li class="large">Si vous pouvez héberger ou si vous souhaitez être hébergé</li>
    </ul>
    <br /><br />
    """
    buttonText = "Envoyer le message"

    email = "breizhcoastswing@gmail.com"

    # Success and error message overwrite for async contact form
    thanks = "Merci de nous avoir contacté!"
    error = """Votre message ne peut malheureusement être envoyé.<br />
      Veuillez retentez utltérieurement."""

    # 'warning' defines error messages for invalid inputs
    [params.registration.form.lastname]
      text = "Votre Nom *"
      warning = "Veuillez saisir votre nom."

    [params.registration.form.firstname]
      text = "Votre Prénom *"
      warning = "Veuillez saisir votre prénom."

    [params.registration.form.email]
      text = "Votre Email *"
      warning = "Veuillez saisir votre adresse email."

    [params.registration.form.message]
      text = "Votre message *"
      warning = "Veuillez saisir votre message."

  # Footer section
  [params.footer]
    enable = true

  [[params.footer.social]]
    icon = "fa-facebook"
    link = "https://www.facebook.com/events/1612524012165504/"
